services:
  api-gateway:
    build: .
    ports:
      - "3000:3000"
    environment:
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization
      - CORS_ALLOW_ORIGINS=*
      # Add other environment variables as needed 

  account-service:
    build: ../AccountService
    ports:
      - "8000:8000"
    environment:
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization
      - CORS_ALLOW_ORIGINS=*
      # Add other environment variables as needed

  policy-service:
    build: ../PolicyService
    ports:
      - "8001:8001"

  rating-service:
    build: ../RatingService
    ports:
      - "8002:8002"
    environment:
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization
      - CORS_ALLOW_ORIGINS=*
      # Add other environment variables as needed 

  transaction-service:
    build: ../TransactionService
    ports:
      - "8003:8003"
    environment:
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization
      - CORS_ALLOW_ORIGINS=*
      # Add other environment variables as needed 

  workflow-service:
    build: ../WorkflowService/
    ports:
      - "8004:8004"
    environment:
      - CORS_ALLOW_HEADERS=Origin,Content-Type,Accept,Authorization
      - CORS_ALLOW_ORIGINS=*
      # Add other environment variables as needed 

  policyprocessor-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "$${development.PolicyProcessorDB.User}"
      POSTGRES_PASSWORD: "$${development.PolicyProcessorDB.Password}"
      POSTGRES_DB: "PolicyProcessorDB"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 2

  rate-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "$${development.RateDB.User}"
      POSTGRES_PASSWORD: "$${development.RateDB.Password}"
      POSTGRES_DB: "RateDB"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 2
