env: development

development:
  cors:
    allow_headers: "Origin,Content-Type,Accept,authorization"
    allow_origins: "*"
    allow_credentials: false
    allow_methods: "GET,POST,HEAD,PUT,DELETE,PATCH,OPTIONS"
  RateDB:
    host: "localhost"
    user: "postgres"
    password: "readonly"
    dbname: "RateDB"
    port: 5432
    sslmode: "disable"
  PolicyProcessorDB:
    host: "localhost"
    user: "postgres"
    password: "readonly"
    dbname: "PolicyProcessorDB"
    port: 5432
    sslmode: "disable"
  ThirdPartyDB:
    host: "localhost"
    user: "postgres"
    password: "readonly"
    dbname: "ThirdPartyDB"
    port: 5432
    sslmode: "disable"
  timezone: "UTC"

production:
  cors:
    allow_headers: "Origin,Content-Type,Accept,authorization"
    allow_origins:  "*"
    allow_credentials: true
    allow_methods: "GET,POST,HEAD,PUT,DELETE,PATCH,OPTIONS"
  rate_database:
    host: "localhost"
    user: "postgres"
    password: "readonly"
    dbname: "RateDB"
    port: 5432
    sslmode: "disable"
  PolicyProcessorDB:
    host: "localhost"
    user: "postgres"
    password: "readonly"
    dbname: "PolicyProcessorDB"
    port: 5432
    sslmode: "disable"
  third_party_database:
    host: "localhost"
    user: "postgres"
    password: "readonly"
    dbname: "ThirdPartyDB"
    port: 5432
    sslmode: "disable"
  timezone: "UTC"


base_dir: /Users/harishmurali/PolicyProcessor_V1.0/PolicyProcessor_API

policy_service_port: 8001
transaction_service_port: 8003
account_service_port: 8000
rating_service_port: 8002
workflow_service_port: 8004